USE MASTER 
GO

CREATE DATABASE DB_VENDAS
ON 
(
NAME = DB_Vendas_DAT,
FILENAME=N'C:\Users\ta0503\Documents\Sinqia_AspNet\DB_VENDAS.MDF',
SIZE = 5000KB,
MAXSIZE=UNLIMITED,
FILEGROWTH=1000KB
)

LOG ON 
(
NAME = DB_Vendas_LOG,
FILENAME=N'C:\Users\ta0503\Documents\Sinqia_AspNet\DB_VENDAS_log.ldf',
SIZE = 2000KB,
MAXSIZE=UNLIMITED,
FILEGROWTH=1000KB
);
GO